### ISSUE TITLE
CWE-23:Path Traversal Vulnerability at Line 486 in AutoExtract.java

### ISSUE THREAD

**Issue by sneha17-hub** [rilling/robocodeFall2024#102]
**Describe the Software Vulnerability**
The deleteDir method in AutoExtract.java (line 486) contains a Path Traversal vulnerability. Unsanitized input from a command-line argument is used directly in the listFiles() method without validation. This allows an attacker to potentially manipulate arbitrary files or directories by supplying malicious paths.

**Type of Vulnerability**
The vulnerability is a Path Traversal issue caused by unsafe handling of directory paths in the listFiles() method. This was identified using Snyk Code analysis tools, which flagged the unsafe use of listFiles without validation of the provided directory path.

**CVE**
**CWE-23: Relative Path Traversal**
This issue corresponds to the CWE-23 vulnerability, which occurs when user-controlled input is used to navigate or access files and directories improperly.

**Expected outcome**
The vulnerability will be patched by:

Adding a null check and fallback to ensure listFiles() does not process unsafe or invalid directory inputs.
Preventing NullPointerException and enforcing stricter path validation to mitigate the Path Traversal risk.

**Code before refactoring**
Below is a screenshot of the vulnerable code before applying the fix:
![Screen Shot 2024-11-30 at 4 25 48 PM](https://github.com/user-attachments/assets/3c840f48-1038-4ef0-88ae-e1099ca544d3)

**Code after refactoring**
The issue is fixed by modifying line 486 to include a null check and ensure safe handling of the directory list. The updated code snippet is as follows:
![Screen Shot 2024-11-30 at 4 27 40 PM](https://github.com/user-attachments/assets/dac0dfd7-c3a4-4294-8778-f80c00756f43)

for (File file : (dir != null && dir.isDirectory() ? dir.listFiles() : new File[0])) {
This ensures that dir.listFiles() is only called on a valid directory and defaults to an empty array if invalid input is detected.

**Additional context**
This fix was applied as part of PR [#40](https://github.com/Amanpreet1304/robocodeFall2024/pull/40). The change mitigates the flagged vulnerability without altering the core logic of the deleteDir method. This refactoring was done with minimal disruption to ensure the security and functionality of the method.

**Comment by rkerw** [comment]
fixed by #110
