### ISSUE TITLE
Eliminate Code Duplication in Battle.java (lines 665 & 686)

### ISSUE THREAD

**Issue by YajingLiu2357** [rilling/robocodeFall2024#29]
**Describe the clone**
Eliminate Code Duplication in Battle.java (lines 665 & 686)

**Location of the clones**
Starting at line 665 of robocodeFall2024/robocode.battle/src/main/java/net/sf/robocode/battle/Battle.java
Starting at line 686 of robocodeFall2024/robocode.battle/src/main/java/net/sf/robocode/battle/Battle.java

**Clone Type**
Type 1 clone

**Expected outcome**
Extract the duplicated codes into a single method

**Code before refactoring**
![Screenshot 2024-11-09 at 3 41 09 PM](https://github.com/user-attachments/assets/23e7091e-17e5-48fa-98de-6d1e5afd057f)

**Code after refactoring**
![image](https://github.com/user-attachments/assets/b338a8f6-af80-4d82-a59c-a8cf464515c0)

**Additional context**
N/A

**Comment by Beavan1997** [comment]
Code before refactoring
![image](https://github.com/user-attachments/assets/ef0aa757-1a57-47b9-9f44-2bcfc0cbb221)

Code after refactoring
![image](https://github.com/user-attachments/assets/b338a8f6-af80-4d82-a59c-a8cf464515c0)

[Link](https://github.com/YajingLiu2357/robocodeFall2024/issues/43#issue-2647912658) to Issue on the Group 11 Forked Repository
