### ISSUE TITLE
Directory Traversal attack in ‎robocode.repository/JarExtractor.java

### ISSUE THREAD

**Issue by YajingLiu2357** [rilling/robocodeFall2024#83]
**Describe the Software Vulnerability**
Unsanitized input from a zip file flows into java.io.FileOutputStream, where it is used as a path. This may result in a Path Traversal vulnerability and allow an attacker to write to arbitrary files.

**Type of Vulnerability**
A Directory Traversal attack (also known as path traversal) aims to access files and directories that are stored outside the intended folder. By manipulating files with "dot-dot-slash (../)" sequences and its variations, or by using absolute file paths, it may be possible to access arbitrary files and directories stored on file system, including application source code, configuration, and other critical system files.

Being able to access and manipulate an arbitrary path leads to vulnerabilities when a program is being run with privileges that the user providing the path should not have. A website with a path traversal vulnerability would allow users access to sensitive files on the server hosting it. CLI programs may also be vulnerable to path traversal if they are being ran with elevated privileges (such as with the setuid or setgid flags in Unix systems).

**CVE**
CWE-23: Relative Path Traversal

**File Path**
‎robocode.repository/src/main/java/net/sf/robocode/repository/packager/JarExtractor.java

**Expected outcome**
Valid the filename to ensure that it does not contain any unintended path traversal sequences or attempt to write outside the desired directory.

**Code before refactoring**
<img width="714" alt="Screenshot 2024-11-23 at 3 39 18 PM" src="https://github.com/user-attachments/assets/dcb9cb06-9761-4edb-826f-9b1c6692f5d1">

**Code after refactoring**
![image](https://github.com/user-attachments/assets/bee673bb-7f29-4ea0-9c47-48f0ccdffaf2)

**Additional context**
N/A

**Comment by Beavan1997** [comment]
**Code after refactoring**

![image](https://github.com/user-attachments/assets/bee673bb-7f29-4ea0-9c47-48f0ccdffaf2)
